"""Markdown report generator for SparkAutoEDA (GitHub flavored)."""

from typing import Dict, Any


def render_markdown(profile_data: Dict[str, Any]) -> str:
    """Generate a clean, professional GitHub-compatible Markdown summary report."""
    ov = profile_data.get("overview", {})
    quality = profile_data.get("quality", {})
    col_stats = profile_data.get("column_stats", {})
    corr = profile_data.get("correlations", {})
    col_classes = profile_data.get("column_classes", {})

    lines = []

    # Title & Metadata
    lines.append("# ⚡ SparkAutoEDA: Automated Dataset Profile Report")
    lines.append("")
    lines.append(
        f"> **Generated by [SparkAutoEDA](https://github.com/open-source/spark-auto-eda)** | "
        f"Distributed PySpark Data Profiler"
    )
    lines.append("")

    # Overall Metrics Table
    lines.append("## 📊 Executive Overview")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| :--- | :--- |")
    lines.append(f"| **Total Rows** | {ov.get('total_rows', 0):,} |")
    lines.append(f"| **Total Columns** | {ov.get('total_columns', 0):,} |")
    lines.append(f"| **PySpark Partitions** | {ov.get('partitions', 0)} |")
    lines.append(f"| **Duplicate Rows** | {ov.get('duplicate_rows', 0):,} ({ov.get('duplicate_percentage', 0)}%) |")
    lines.append(f"| **Est. Memory Size** | {ov.get('memory_info', {}).get('estimated_readable', 'N/A')} |")
    lines.append(f"| **Numerical Features** | {ov.get('numerical_columns', 0)} |")
    lines.append(f"| **Categorical Features** | {ov.get('categorical_columns', 0)} |")
    lines.append(f"| **Datetime Features** | {ov.get('datetime_columns', 0)} |")
    lines.append(f"| **Data Health Score** | **{quality.get('health_score', 100)} / 100** ({quality.get('health_status', 'Good')}) |")
    lines.append("")

    # Quality Alerts
    alerts = quality.get("alerts", [])
    if alerts:
        lines.append("## 🚨 Data Health & Quality Alerts")
        lines.append("")
        for alert in alerts:
            sev = alert["severity"]
            col = alert["column"]
            msg = alert["message"]
            if sev == "CRITICAL":
                lines.append(f"> [!CAUTION]")
                lines.append(f"> **[{col}] CRITICAL**: {msg}")
            elif sev == "WARNING":
                lines.append(f"> [!WARNING]")
                lines.append(f"> **[{col}] WARNING**: {msg}")
            else:
                lines.append(f"> [!NOTE]")
                lines.append(f"> **[{col}] INFO**: {msg}")
            lines.append("")

    # Numerical Column Deep-Dives
    num_cols = col_classes.get("numerical", [])
    if num_cols:
        lines.append("## 📈 Numerical Feature Distributions")
        lines.append("")
        lines.append("| Column | Missing (%) | Mean | StdDev | Min | Median | Max | Outliers (%) |")
        lines.append("| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |")
        for col in num_cols:
            st = col_stats.get(col, {})
            mean_str = f"{st.get('mean', 0.0):.2f}" if st.get("mean") is not None else "N/A"
            std_str = f"{st.get('stddev', 0.0):.2f}" if st.get("stddev") is not None else "N/A"
            min_str = f"{st.get('min', 0.0):.2f}" if st.get("min") is not None else "N/A"
            med_str = f"{st.get('median', 0.0):.2f}" if st.get("median") is not None else "N/A"
            max_str = f"{st.get('max', 0.0):.2f}" if st.get("max") is not None else "N/A"
            lines.append(
                f"| `{col}` | {st.get('missing_percentage', 0)}% | {mean_str} | {std_str} | {min_str} | {med_str} | {max_str} | {st.get('outlier_percentage', 0)}% |"
            )
        lines.append("")

    # Categorical Column Summaries
    cat_cols = col_classes.get("categorical", []) + col_classes.get("boolean", [])
    if cat_cols:
        lines.append("## 🏷️ Categorical & Boolean Features")
        lines.append("")
        lines.append("| Column | Type | Distinct | Missing (%) | Top Values (Freq %) |")
        lines.append("| :--- | :---: | :---: | :---: | :--- |")
        for col in cat_cols:
            st = col_stats.get(col, {})
            top_vals = st.get("top_values", [])
            top_summary = ", ".join([f"`{v['value']}` ({v['percentage']}%)" for v in top_vals[:3]])
            lines.append(
                f"| `{col}` | {st.get('data_type', 'string')} | {st.get('distinct_count', 0):,} | {st.get('missing_percentage', 0)}% | {top_summary or 'N/A'} |"
            )
        lines.append("")

    # Datetime Columns
    dt_cols = col_classes.get("datetime", [])
    if dt_cols:
        lines.append("## ⏰ Datetime Features")
        lines.append("")
        lines.append("| Column | Earliest Timestamp | Latest Timestamp | Missing (%) |")
        lines.append("| :--- | :--- | :--- | :---: |")
        for col in dt_cols:
            st = col_stats.get(col, {})
            lines.append(
                f"| `{col}` | {st.get('min_time', 'N/A')} | {st.get('max_time', 'N/A')} | {st.get('missing_percentage', 0)}% |"
            )
        lines.append("")

    # Collinear Features
    collinear = corr.get("collinear_pairs", [])
    if collinear:
        lines.append("## 🔗 Highly Collinear Feature Pairs (|r| ≥ 0.90)")
        lines.append("")
        lines.append("| Feature 1 | Feature 2 | Pearson Correlation (r) |")
        lines.append("| :--- | :--- | :---: |")
        for pair in collinear:
            lines.append(f"| `{pair['feature_a']}` | `{pair['feature_b']}` | **{pair['correlation']:.2f}** |")
        lines.append("")

    lines.append("---")
    lines.append("*Generated with ❤️ by [SparkAutoEDA](https://github.com/open-source/spark-auto-eda) — Distributed Big Data Profiling*")

    return "\n".join(lines)
